import { defineStore } from 'pinia'
import { formatCountdown } from '@/utils/datetime'

/**
 * In-app notifications (session-scoped):
 *  - someone joined an event you host
 *  - an event you joined was edited or cancelled
 *  - an event you joined starts within the hour
 * Generated by diffing realtime event updates in eventStore, plus a
 * once-a-minute starting-soon check from MapView.
 */
export const useNotifStore = defineStore('notifications', {
  state: () => ({
    // { id, text, eventId, dm, at, read } — `dm` is { threadId, peerId }
    // for message alerts, which route to a conversation instead of a pin
    items: [],
    soonNotified: new Set(),
    toast: '',
    toastTimer: null
  }),

  getters: {
    unreadCount: (state) => state.items.filter((n) => !n.read).length
  },

  actions: {
    push(text, eventId, dm = null) {
      this.items.unshift({
        id: `n-${Date.now().toString(36)}-${this.items.length}`,
        text,
        eventId,
        dm,
        at: new Date().toISOString(),
        read: false
      })
      if (this.items.length > 30) this.items.length = 30
    },

    /** A direct message arrived while I was somewhere else in the app. */
    announceDm(message, senderName) {
      this.push(`💬 ${senderName} sent you a message`, null, {
        threadId: message.threadId,
        peerId: message.senderId
      })
    },

    markAllRead() {
      this.items.forEach((n) => {
        n.read = true
      })
    },

    clearAll() {
      this.items = []
    },

    /** Transient on-map confirmation banner ("You're in — see you there!"). */
    flash(text) {
      this.toast = text
      clearTimeout(this.toastTimer)
      this.toastTimer = setTimeout(() => {
        this.toast = ''
      }, 4000)
    },

    /** Diff one event's previous vs next state for things worth telling me. */
    diffEvent(prev, next, meId, nameOf) {
      if (!prev || !next || !meId) return

      if (next.hostId === meId) {
        for (const id of next.attendeeIds) {
          if (id !== meId && !prev.attendeeIds.includes(id)) {
            this.push(`${nameOf(id)} joined "${next.title}"`, next.id)
          }
        }
        for (const id of next.requestedIds || []) {
          if (!(prev.requestedIds || []).includes(id)) {
            this.push(`🙋 ${nameOf(id)} requested to join "${next.title}"`, next.id)
            this.flash(`🙋 ${nameOf(id)} requested to join "${next.title}"`)
          }
        }
        return
      }

      // My pending request got a verdict
      const wasRequested = (prev.requestedIds || []).includes(meId)
      if (wasRequested && next.attendeeIds.includes(meId)) {
        this.push(`✅ Request approved — you're in for "${next.title}"!`, next.id)
        this.flash(`✅ You're approved for "${next.title}"!`)
        return
      }
      if (
        wasRequested &&
        !(next.requestedIds || []).includes(meId) &&
        !next.attendeeIds.includes(meId)
      ) {
        this.push(`Your request for "${next.title}" was declined`, next.id)
        return
      }

      if (prev.attendeeIds.includes(meId)) {
        const changed =
          prev.startsAt !== next.startsAt ||
          prev.title !== next.title ||
          prev.locationName !== next.locationName
        if (changed) this.push(`"${next.title}" was updated by the host`, next.id)
        // Promoted off the waitlist into the guestlist
        if (!prev.attendeeIds.includes(meId) && next.attendeeIds.includes(meId)) {
          this.push(`A spot opened up — you're in for "${next.title}"!`, next.id)
        }
      } else if (prev.waitlistIds?.includes(meId) && next.attendeeIds.includes(meId)) {
        this.push(`A spot opened up — you're in for "${next.title}"!`, next.id)
      }
    },

    /**
     * A host I follow just posted something new — the payoff for the
     * "Notify me of their next event" promise.
     */
    announceNewEvent(event, meId, isFollowed, nameOf) {
      if (!meId || event.hostId === meId || !isFollowed?.(event.hostId)) return
      const who = nameOf(event.hostId)
      this.push(`🔔 ${who} just posted "${event.title}"`, event.id)
      this.flash(`🔔 ${who} just posted a new event`)
    },

    /** Full-snapshot diff (live mode SYNC): joins on my events + cancellations. */
    diffSnapshot(prevEvents, nextEvents, meId, nameOf, isFollowed) {
      if (!meId) return
      const nextById = new Map(nextEvents.map((e) => [e.id, e]))
      const prevIds = new Set(prevEvents.map((e) => e.id))
      for (const prev of prevEvents) {
        const next = nextById.get(prev.id)
        if (!next) {
          if (prev.hostId !== meId && prev.attendeeIds.includes(meId)) {
            this.push(`"${prev.title}" was cancelled`, null)
          }
          continue
        }
        this.diffEvent(prev, next, meId, nameOf)
      }
      // Events that appeared in this snapshot: announce followed hosts'
      for (const next of nextEvents) {
        if (!prevIds.has(next.id)) {
          this.announceNewEvent(next, meId, isFollowed, nameOf)
        }
      }
    },

    /** Called every minute: events I'm going to that start within the hour. */
    checkStartingSoon(events, meId) {
      if (!meId) return
      const now = Date.now()
      for (const event of events) {
        if (!event.attendeeIds.includes(meId)) continue
        const diff = new Date(event.startsAt).getTime() - now
        if (diff > 0 && diff <= 3600000 && !this.soonNotified.has(event.id)) {
          this.soonNotified.add(event.id)
          this.push(`"${event.title}" — ${formatCountdown(event.startsAt)}`, event.id)
        }
      }
    }
  }
})
